SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Tables */

DROP TABLE FG_THANKS_HISTORY_TABLE;
DROP TABLE FG_BOOK_REVIEW_TABLE;
DROP TABLE FG_RECOMMEND_TABLE;
DROP TABLE FG_BOOK_TABLE;
DROP TABLE FG_AUTHOR_TABLE;
DROP TABLE FG_FOLLOW_TABLE;
DROP TABLE FG_USER_REG_TABLE;
DROP TABLE FG_USER_TABLE;
DROP TABLE FG_MJOB_TABLE;
DROP TABLE FG_LJOB_TABLE;




/* Create Tables */

CREATE TABLE FG_AUTHOR_TABLE
(
	AUTHOR_ID INT NOT NULL AUTO_INCREMENT,
	AUTHOR_NAME VARCHAR(100) UNIQUE,
	USER_ID CHAR(100) NOT NULL,
	RDATE DATETIME,
	UDATE TIMESTAMP DEFAULT NOW(), SYSDATE(),
	PRIMARY KEY (AUTHOR_ID)
);


CREATE TABLE FG_BOOK_REVIEW_TABLE
(
	BOOK_REVIEW_NO INT NOT NULL,
	BOOK_REVIEW LONGTEXT,
	BOOK_ID INT NOT NULL,
	-- カンマ区切りで複数指定可
	TAG VARCHAR(1000) COMMENT 'カンマ区切りで複数指定可',
	FEELING VARCHAR(100) NOT NULL,
	THANKS_CNT INT DEFAULT 0 NOT NULL,
	USER_ID CHAR(100) NOT NULL,
	RDATE DATETIME,
	UDATE TIMESTAMP DEFAULT NOW(), SYSDATE(),
	PRIMARY KEY (BOOK_REVIEW_NO)
);


CREATE TABLE FG_BOOK_TABLE
(
	BOOK_ID INT NOT NULL AUTO_INCREMENT,
	BOOK_NAME VARCHAR(255),
	-- 国際標準図書番号（日本図書コード・書籍JANコード）
	ISBN CHAR(50) COMMENT '国際標準図書番号（日本図書コード・書籍JANコード）',
	IMAGEURL VARCHAR(500),
	AUTHOR_ID INT NOT NULL,
	DETAILPAGEURL VARCHAR(1000),
	USER_ID CHAR(100) NOT NULL,
	RDATE DATETIME,
	UDATE TIMESTAMP DEFAULT NOW(), SYSDATE(),
	PRIMARY KEY (BOOK_ID)
);


CREATE TABLE FG_FOLLOW_TABLE
(
	FOLLOW_USER_ID CHAR(100) NOT NULL,
	-- フォローしたユーザー
	USER_ID CHAR(100) NOT NULL COMMENT 'フォローしたユーザー',
	DELETE_FLG INT,
	RDATE DATETIME,
	UDATE TIMESTAMP DEFAULT NOW(), SYSDATE(),
	PRIMARY KEY (FOLLOW_USER_ID, USER_ID)
);


CREATE TABLE FG_LJOB_TABLE
(
	LJOB_CD CHAR(5) NOT NULL,
	LJOB_NAME VARCHAR(255),
	PRIMARY KEY (LJOB_CD)
);


CREATE TABLE FG_MJOB_TABLE
(
	MJOB_CD CHAR(5) NOT NULL,
	LJOB_CD CHAR(5) NOT NULL,
	MJOB_NAME VARCHAR(255) NOT NULL,
	PRIMARY KEY (MJOB_CD, LJOB_CD)
);


CREATE TABLE FG_RECOMMEND_TABLE
(
	RECO_NO INT NOT NULL AUTO_INCREMENT,
	USER_ID CHAR(24) NOT NULL,
	BOOK_ID INT NOT NULL,
	RDATE DATETIME,
	UDATE TIMESTAMP DEFAULT NOW(), SYSDATE(),
	PRIMARY KEY (RECO_NO, USER_ID)
);


CREATE TABLE FG_THANKS_HISTORY_TABLE
(
	BOOK_REVIEW_NO INT NOT NULL,
	-- Thanksボタンをクリックしたユーザー
	USER_ID CHAR(100) NOT NULL COMMENT 'Thanksボタンをクリックしたユーザー',
	-- 1:削除
	DELETE_FLG INT COMMENT '1:削除',
	RDATE DATETIME,
	UDATE TIMESTAMP DEFAULT NOW(), SYSDATE(),
	PRIMARY KEY (BOOK_REVIEW_NO, USER_ID)
);


CREATE TABLE FG_USER_REG_TABLE
(
	USER_ID CHAR(24) NOT NULL,
	PASSWORD CHAR(24),
	NICKNAME VARCHAR(50),
	BIRTH DATE,
	-- M:男性、F:女性
	GENDER CHAR(1) COMMENT 'M:男性、F:女性',
	MJOB_CD CHAR(5) NOT NULL,
	LJOB_CD CHAR(5) NOT NULL,
	RKEY VARCHAR(50),
	RDATE DATETIME,
	-- 1:本登録済
	STATUS INT COMMENT '1:本登録済',
	PRIMARY KEY (USER_ID)
);


CREATE TABLE FG_USER_TABLE
(
	USER_ID CHAR(24) NOT NULL,
	PASSWORD CHAR(24),
	NICKNAME VARCHAR(50),
	BIRTH DATE,
	-- M:男性、F:女性
	GENDER CHAR(1) COMMENT 'M:男性、F:女性',
	MJOB_CD CHAR(5) NOT NULL,
	LJOB_CD CHAR(5) NOT NULL,
	PREMIUM_DEGREE INT,
	-- 書評投稿数
	REVIEW_POSTS_CNT INT COMMENT '書評投稿数',
	-- 「ありがとう」獲得数
	THANKS_CNT INT COMMENT '「ありがとう」獲得数',
	FOLLOW_CNT INT,
	FOLLOWER_CNT INT,
	RDATE DATETIME,
	UDATE TIMESTAMP DEFAULT NOW(), SYSDATE(),
	PRIMARY KEY (USER_ID)
);



/* Create Foreign Keys */

ALTER TABLE FG_BOOK_TABLE
	ADD FOREIGN KEY (AUTHOR_ID)
	REFERENCES FG_AUTHOR_TABLE (AUTHOR_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE FG_THANKS_HISTORY_TABLE
	ADD FOREIGN KEY (BOOK_REVIEW_NO)
	REFERENCES FG_BOOK_REVIEW_TABLE (BOOK_REVIEW_NO)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE FG_BOOK_REVIEW_TABLE
	ADD FOREIGN KEY (BOOK_ID)
	REFERENCES FG_BOOK_TABLE (BOOK_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE FG_RECOMMEND_TABLE
	ADD FOREIGN KEY (BOOK_ID)
	REFERENCES FG_BOOK_TABLE (BOOK_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE FG_MJOB_TABLE
	ADD FOREIGN KEY (LJOB_CD)
	REFERENCES FG_LJOB_TABLE (LJOB_CD)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE FG_USER_REG_TABLE
	ADD FOREIGN KEY (MJOB_CD, LJOB_CD)
	REFERENCES FG_MJOB_TABLE (MJOB_CD, LJOB_CD)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE FG_USER_TABLE
	ADD FOREIGN KEY (MJOB_CD, LJOB_CD)
	REFERENCES FG_MJOB_TABLE (MJOB_CD, LJOB_CD)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE FG_RECOMMEND_TABLE
	ADD FOREIGN KEY (USER_ID)
	REFERENCES FG_USER_TABLE (USER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE FG_USER_REG_TABLE
	ADD FOREIGN KEY (USER_ID)
	REFERENCES FG_USER_TABLE (USER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



