SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Tables */

DROP TABLE BOOK_REVIEW_TABLE;
DROP TABLE RECOMMEND_TABLE;
DROP TABLE BOOK_TABLE;
DROP TABLE AUTHOR_TABLE;
DROP TABLE USER_REG_TABLE;
DROP TABLE USER_TABLE;
DROP TABLE MJOB_TABLE;
DROP TABLE LJOB_TABLE;




/* Create Tables */

CREATE TABLE AUTHOR_TABLE
(
	AUTHOR_ID INT NOT NULL AUTO_INCREMENT,
	AUTHOR_NAME VARCHAR(100) UNIQUE,
	RDATE DATETIME,
	UDATE TIMESTAMP DEFAULT NOW(), SYSDATE(),
	PRIMARY KEY (AUTHOR_ID)
);


CREATE TABLE BOOK_REVIEW_TABLE
(
	BOOK_REVIEW_NO INT NOT NULL AUTO_INCREMENT,
	BOOK_REVIEW LONGTEXT,
	BOOK_ID INT NOT NULL,
	-- カンマ区切りで複数指定可
	BOOK_TAG VARCHAR(1000) COMMENT 'カンマ区切りで複数指定可',
	RDATE DATETIME,
	UDATE TIMESTAMP DEFAULT NOW(), SYSDATE(),
	PRIMARY KEY (BOOK_REVIEW_NO)
);


CREATE TABLE BOOK_TABLE
(
	BOOK_ID INT NOT NULL AUTO_INCREMENT,
	BOOK_NAME VARCHAR(255),
	-- 国際標準図書番号（日本図書コード・書籍JANコード）
	ISBN CHAR(50) COMMENT '国際標準図書番号（日本図書コード・書籍JANコード）',
	AUTHOR_ID INT NOT NULL,
	RDATE DATETIME,
	UDATE TIMESTAMP DEFAULT NOW(), SYSDATE(),
	PRIMARY KEY (BOOK_ID)
);


CREATE TABLE LJOB_TABLE
(
	LJOB_CD CHAR(5) NOT NULL,
	LJOB_NAME VARCHAR(255),
	PRIMARY KEY (LJOB_CD)
);


CREATE TABLE MJOB_TABLE
(
	MJOB_CD CHAR(5) NOT NULL,
	LJOB_CD CHAR(5) NOT NULL,
	MJOB_NAME VARCHAR(255) NOT NULL,
	PRIMARY KEY (MJOB_CD, LJOB_CD)
);


CREATE TABLE RECOMMEND_TABLE
(
	RECO_NO INT NOT NULL AUTO_INCREMENT,
	USER_ID CHAR(24) NOT NULL,
	BOOK_ID INT NOT NULL,
	RDATE DATETIME,
	UDATE TIMESTAMP DEFAULT NOW(), SYSDATE(),
	PRIMARY KEY (RECO_NO, USER_ID)
);


CREATE TABLE USER_REG_TABLE
(
	USER_ID CHAR(24) NOT NULL,
	PASSWORD CHAR(24),
	NICKNAME VARCHAR(50),
	BIRTH DATE,
	GENDER INT,
	MJOB_CD CHAR(5) NOT NULL,
	LJOB_CD CHAR(5) NOT NULL,
	RKEY VARCHAR(50),
	RDATE DATETIME,
	PRIMARY KEY (USER_ID)
);


CREATE TABLE USER_TABLE
(
	USER_ID CHAR(24) NOT NULL,
	PASSWORD CHAR(24),
	NICKNAME VARCHAR(50),
	BIRTH DATE,
	-- 0:不明、1:男性、2:女性
	GENDER INT COMMENT '0:不明、1:男性、2:女性',
	MJOB_CD CHAR(5) NOT NULL,
	LJOB_CD CHAR(5) NOT NULL,
	PREMIUM_DEGREE INT,
	-- 書評投稿数
	REVIEW_POSTS_CNT INT COMMENT '書評投稿数',
	-- 「ありがとう」獲得数
	THANKS_CNT INT COMMENT '「ありがとう」獲得数',
	FOLLOW_CNT INT,
	FOLLOWER_CNT INT,
	RDATE DATETIME,
	UDATE TIMESTAMP DEFAULT NOW(), SYSDATE(),
	PRIMARY KEY (USER_ID)
);



/* Create Foreign Keys */

ALTER TABLE BOOK_TABLE
	ADD FOREIGN KEY (AUTHOR_ID)
	REFERENCES AUTHOR_TABLE (AUTHOR_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE BOOK_REVIEW_TABLE
	ADD FOREIGN KEY (BOOK_ID)
	REFERENCES BOOK_TABLE (BOOK_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE RECOMMEND_TABLE
	ADD FOREIGN KEY (BOOK_ID)
	REFERENCES BOOK_TABLE (BOOK_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE MJOB_TABLE
	ADD FOREIGN KEY (LJOB_CD)
	REFERENCES LJOB_TABLE (LJOB_CD)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USER_REG_TABLE
	ADD FOREIGN KEY (MJOB_CD, LJOB_CD)
	REFERENCES MJOB_TABLE (MJOB_CD, LJOB_CD)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USER_TABLE
	ADD FOREIGN KEY (MJOB_CD, LJOB_CD)
	REFERENCES MJOB_TABLE (MJOB_CD, LJOB_CD)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE RECOMMEND_TABLE
	ADD FOREIGN KEY (USER_ID)
	REFERENCES USER_TABLE (USER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USER_REG_TABLE
	ADD FOREIGN KEY (USER_ID)
	REFERENCES USER_TABLE (USER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



